defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: small_budget
  - override /task@_global_: agent_design
  - override /cluster@_global_: local
  - _self_

variant_suffix: "_example"

evo_config:
  llm_models:
    - "azure-gpt-4.1-mini"