defaults:
  - override /database@_global_: island_large
  - override /evolution@_global_: large_budget
  - override /task@_global_: sdpa
  - override /cluster@_global_: local
  - _self_

variant_suffix: "_example"

